spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
lotto:
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      count: 25
      lower-bound: 1
      upper-bound: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80