spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
lotto:
  number-generator:
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80