spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
lotto:
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      count: 25
      lowerBound: 1
      upperBound: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
